services:
  pmg:
    hostname: pmg
    container_name: pmg
    image: dockurr/proxmox-mail
    environment:
      TZ: "UTC"
      PASSWORD: "root"
      DOMAIN: "pmg.example.com"
    ports:
      - 25:25
      - 26:26
      - 8006:8006
    volumes:
      - ./config:/etc/pmg
      - ./data:/var/lib/pmg
      - ./spool:/var/spool/pmg
      - ./postgres:/var/lib/postgresql
    restart: always
    stop_grace_period: 2m
