services:
  pdm:
    hostname: pdm
    container_name: pdm
    image: dockurr/proxmox-dm
    environment:
      PASSWORD: "root"
    ports:
      - 8443:8443
    volumes:
      - ./config:/etc/proxmox-datacenter-manager
      - ./pdm:/var/lib/proxmox-datacenter-manager
    restart: always
    privileged: true
    stop_grace_period: 2m
